on:
  push:
    branches:
      - main
jobs:
  execute-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/setup-aws-cli@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Test AWS CLI
        run: |
          aws configure list-profiles

      - name: Test moving to ~
        run: |
          cd ~
          ls
          pwd
