on:
  push:
    branches:
      - main
jobs:
  execute-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install react dependencies
        run: |
          cd ./front_end
          npm install
          echo "Install complete"
          ls

      - name: Build React Project
        run: |
          cd ./front_end
          npm run build
          echo "Build Complete"
          ls