## Checkout https://dev.to/zirkelc/trigger-github-workflow-for-comment-on-pull-request-45l2

on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'Deploy' }}
    runs-on: ubuntu-latest

    steps:

      - name: Get PR details
        id: get_pr
        run: |
          PR=$(curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "${{ github.event.issue.pull_request.url }}")
          echo "::set-output name=branch::$(echo "$PR" | jq -r .head.ref)"


      # Checkout the branch in the PR to run changes
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print file structure
        run: |
          ls
          pwd
