on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'Deploy' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Change to Infra directory
        run: cd /home/runner/work/password_generator_webapp/password_generator_webapp/Infra

      - name: Terrafrom configuration check
        id: fmt
        run: |
          terraform fmt -check
          ls
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: |
          terraform init
          ls

      - name: Terraform Validate
        id: validate
        run: |
          terraform validate
          ls

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan
          ls
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve

        env:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1