## This trigger will only be triggered when we want to destroy the whole architecture.
on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/Destroy-all' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      pull-requests: read
      statuses: write

    steps:
      - uses: hashicorp/setup-terraform@v2

      # The above permission contents, issues and pull-requests permission are needed for this step
      - name: Get PR Branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      # Checkout the branch in the PR to run changes
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      # The above statuses permission are needed for this step.
      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
      
      - name: Set AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Build and zip python requirement file
        id: backend_build
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/back_end
        run: |
          python -m pip install -r requirements.txt -t ./python
          zip -r ../Infra/layer.zip python/
          rm -r python
          python --version

      - name: Terraform Init
        id: init
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: |
          terraform init
          ls

      - name: Terraform Destroy
        id: validate
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: |
          terraform destroy -auto-approve


      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}