## Checkout https://dev.to/zirkelc/trigger-github-workflow-for-comment-on-pull-request-45l2

on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'Deploy' }}
    runs-on: ubuntu-latest

    steps:
      # Initialze git repo
      - name: Checkout
        uses: actions/checkout@v2

      # Checkout the branch in the PR to run changes
      - name: Checkout PR Branch
        run: hub pr checkout ${{github.event.issue.number}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Print file structure
        run: |
          ls
          pwd
