on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'Deploy' }}
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2

      - name: Checkout All Branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get all pull requests
        uses: octokit/rest.js@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          const { data: pullRequests } = await octokit.pulls.list({ owner: 'owner', repo: 'repo', state: 'open' });
          for (const pullRequest of pullRequests) {
            console.log(pullRequest.number);
          }
      - name: Terrafrom configuration check
        id: fmt
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: |
          terraform fmt -check
          ls
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: |
          terraform init
          ls

      - name: Terraform Validate
        id: validate
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: |
          terraform validate
          ls

      - name: Terraform Plan
        id: plan
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: |
          terraform plan
          ls

      - name: Terraform Apply
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: terraform apply -auto-approve

        env:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1