## Checkout https://dev.to/zirkelc/trigger-github-workflow-for-comment-on-pull-request-45l2

on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'Deploy' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: hashicorp/setup-terraform@v2

      - name: Print branch name
        run: echo "Current branch is ${{ github.ref }}"

      - name: Terrafrom configuration check
        id: fmt
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: |
          terraform fmt -check
          ls
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: |
          terraform init
          ls

      - name: Terraform Validate
        id: validate
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: |
          terraform validate
          ls

      - name: Terraform Plan
        id: plan
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: |
          terraform plan
          ls

      - name: Terraform Apply
        working-directory: /home/runner/work/password_generator_webapp/password_generator_webapp/Infra
        run: terraform apply -auto-approve
        
        env:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1