on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'Deploy' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      pull-requests: read
      statuses: write

    steps:
      # Initialze git repo
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get pull request information
        uses: github-actions/pipelines/actions/get-pull-request@v1
        id: get-pr
        with:
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          number: ${{ github.event.issue.number }}

      - name: Print info
        run: |
          echo ${{steps.get-pr.outputs.base-owner}}
          echo ${{steps.get-pr.outputs.head-owner}}

      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: ${{ steps.get-pr.outputs.base-owner }}/${{ github.event.repository.name }}
          ref: ${{ steps.get-pr.outputs.head-ref }}

      - name: Print file structure
        run: |
          ls
          pwd
