on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'Deploy' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      pull-requests: read
      statuses: write

    steps:
      # Initialze git repo
      - name: Checkout
        uses: actions/checkout@v3

      # Checkout the branch in the PR to run changes
      - name: Checkout PR Branch
        run: hub pr checkout ${{github.event.issue.number}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Print file structure
        run: |
          ls
          pwd
